config/routes.rb
Rails.application.routes.draw do
  resources :projects
  root 'projects#index'

  devise_for :users

end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :project_owners
  has_many :users, through: :project_owners

  validates :name, presence: true
end

app/models/project_owner.rb
class ProjectOwner < ActiveRecord::Base
  belongs_to :project
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :email, presence: true, format: { with: /\S+@paytronix.com\z/, message: "must be of the domain paytronix.com.  You must not be cool enough to work there."}

  has_many :project_owners
  has_many :projects, through: :project_owners
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    case params[:status]
    when 'all'
      @projects = Project.all
    when 'completed'
      @projects = Project.where(status: 'completed')
    when 'in development'
      @projects = Project.where(status: 'in development')
    when 'brainstorming'
      @projects = Project.where(status: 'brainstorming')
    else
      @projects = Project.all
    end
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)
    @project.users = [current_user]
    if @project.save
      flash[:notice] = "New project added: #{@project.name}"
      redirect_to projects_path
    else
      flash[:error] = @project.errors.full_messages.join(". ") + "."
      render :new
    end
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private

  def project_params
    params.require(:project).permit(:name, :status, :description)
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SkunkVotes</title>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="title-bar" data-responsive-toggle="example-menu" data-hide-for="medium">
    <button class="menu-icon" type="button" data-toggle></button>
    <div class="title-bar-title">Menu</div>
  </div>

  <div class="top-bar" id="example-menu">
    <div class="top-bar-left">
      <ul class="dropdown menu" data-dropdown-menu>
        <li class="menu-text">SkunkVotes</li>
        <li class="has-submenu">
          <a href="#">Projects</a>
          <ul class="submenu menu vertical" data-submenu>
            <li><%= link_to 'All', projects_path(status: "all") %></li>
            <li><%= link_to 'Completed', projects_path(status: "completed") %></li>
            <li><%= link_to 'Active', projects_path(status: "in development") %></li>
            <li><%= link_to 'Brainstorming', projects_path(status: "brainstorming") %></li>
          </ul>
        </li>
        <li><a href="#">Users</a></li>
        <%- if current_user -%>
          <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
        <%- else -%>
          <li><%= link_to 'Sign Up', new_user_registration_path %></li>
          <li><%= link_to 'Sign In', new_user_session_path %></li>
        <%- end -%>
      </ul>
    </div>
    <div class="top-bar-right">
      <ul class="menu">
        <li><input type="search" placeholder="Search"></li>
        <li><button type="button" class="button">Search</button></li>
      </ul>
    </div>
  </div>

  <%- flash.each do |key, value| -%>
    <div data-alert class="alert-box flash flash-<%= key %>">
      <%= value %>
    </div>
  <%- end -%>

  <%= yield %>

  <%= javascript_include_tag 'application' %>
  <%= yield :extra_footer %>
</body>
</html>

app/views/projects/destroy.html.erb
<h1>ProjectsController#destroy</h1>
<p>Find me in app/views/projects_controller/destroy.html.erb</p>

app/views/projects/edit.html.erb
<h1>ProjectsController#edit</h1>
<p>Find me in app/views/projects_controller/edit.html.erb</p>

app/views/projects/index.html.erb
<ul>
  <% @projects.each do |project| %>
    <li>Project: <%= project.name %>
      <ul>
        <li>Owner(s): <%= project.users[0].email %></li>
        <li>Status: <%= project.status %></li>
        <li>Description: <%= project.description %></li>
      </ul>
    </li>
  <% end %>
</ul>

<%= link_to "New Project", new_project_path, class: "button" %>

app/views/projects/new.html.erb
<h1>New Project</h1>
<%= form_for @project do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :status %>
  <%= f.select :status, [["Completed", "completed"],["In Development", "in development"],["Brainstorming", "brainstorming"]] %>

  <%= f.label :description %>
  <%= f.text_area :description %>

  <%= f.submit %>
<% end %>

app/views/projects/update.html.erb
<h1>ProjectsController#update</h1>
<p>Find me in app/views/projects_controller/update.html.erb</p>